import { styles as s, icon, link, button, eyebrow } from '../ui.js';
import { lessons } from '../lessons.js';

export const lessonCards = (exam) => lessons[exam].map((lesson, index) => `<article class="flex flex-col rounded-2xl border border-line bg-white p-6"><div class="flex justify-between gap-3 text-[11px] font-bold uppercase tracking-wider text-muted"><span>0${index+1} / ${lesson.skill}</span><span class="whitespace-nowrap">${lesson.duration}</span></div><h3 class="mb-4 mt-6 text-xl font-semibold leading-7 tracking-tight">${lesson.title}</h3><p class="mb-6 text-sm leading-6 text-muted">${lesson.concept.split('. ')[0]}.</p><button type="button" data-lesson="${lesson.id}" class="mt-auto flex min-h-12 items-center justify-between border-t border-line pt-4 text-sm font-bold"><span data-lesson-label="${lesson.id}">Open mini-lesson</span>${icon('arrow')}</button></article>`).join('');

import { timer } from '../components.js';
export { timer } from '../components.js';

const essayPlanner = () => `<section id="essay-planner" class="${s.wrap} pb-20"><div class="grid gap-10 lg:grid-cols-2"><div>${eyebrow("Give your ideas a clear direction")}<h2 class="${s.heading}">Plan the argument.<br>Then write the essay.</h2><p class="my-5 text-sm leading-7 text-muted">Choose a Task 2 question type. Build an outline around the actual prompt, with reasons you can explain and examples that support them. The suggested four-part structure is a starting point, not a fixed exam requirement.</p><label for="essay-type" class="${s.label}">Question type<select id="essay-type" class="${s.input}"><option value="opinion">Agree or disagree</option><option value="discussion">Discuss both views</option><option value="problem">Causes and solutions</option><option value="advantages">Advantages outweigh disadvantages</option></select></label><p id="essay-prompt" data-practice lang="en" class="mt-5 rounded-2xl bg-lime/30 p-5 text-sm font-semibold leading-7"></p></div><div><div id="essay-outline" class="space-y-5"></div><p id="essay-status" role="status" class="my-4 text-xs leading-6 text-muted"></p><button type="button" id="download-essay" class="${s.secondary}">Download my outline ${icon("diagonal")}</button></div></div></section>`;

const bandCalculator = () => `<section id="calculator" class="${s.wrap} grid gap-10 pb-20 lg:grid-cols-2"><div>${eyebrow('Understand your four scores')}<h2 class="${s.heading}">See how your<br>overall band adds up.</h2><p class="my-5 max-w-lg text-sm leading-7 text-muted">Enter four component scores to see the rounded average. This calculator does not assess your English or determine whether you meet an institution’s requirements.</p><a href="https://ielts.org/take-a-test/your-results/ielts-scoring-in-detail" class="text-xs font-semibold underline underline-offset-4" target="_blank" rel="noopener">How IELTS calculates the overall band ↗</a></div>
  <div class="rounded-3xl bg-lime/40 p-7"><div class="mb-6 flex items-center justify-between border-b border-ink/20 pb-6"><span class="text-sm font-semibold">Calculated overall band</span><output id="overall-band" aria-live="polite" class="text-5xl font-semibold tracking-tight">7.5</output></div>
  ${[['Listening',7.5],['Reading',8],['Writing',7],['Speaking',7.5]].map(([name,value])=>`<div class="mb-5"><label for="band-${name.toLowerCase()}" class="mb-2 flex justify-between text-sm font-semibold">${name}<output id="value-${name.toLowerCase()}">${value.toFixed(1)}</output></label><input id="band-${name.toLowerCase()}" data-band="${name.toLowerCase()}" type="range" min="0" max="9" step="0.5" value="${value}" class="h-8 w-full accent-ink"></div>`).join('')}</div></section>`;

const speakingDrill = () => `<section id="cue-simulator" class="bg-white"><div class="${s.wrap} grid gap-10 py-20 lg:grid-cols-[1fr_0.85fr]"><div>${eyebrow('Put your learning into words')}<h2 class="${s.heading}">Your next speaking<br>practice starts here.</h2><p class="mt-5 max-w-lg text-sm leading-7 text-muted">Draw an original cue card. Use a minute to prepare, then switch to two minutes for your response. The timer does not record audio.</p><a href="speaking.html" class="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-bold">Explore the speaking studio ${icon('arrow')}</a></div><div><div class="mb-4 rounded-2xl bg-paper p-6"><p id="cue-category" class="text-xs font-semibold text-muted"></p><h3 id="cue-topic" data-practice lang="en" class="my-4 text-xl font-bold leading-7">Describe an electronic device that you find indispensable.</h3><ul id="cue-points" data-practice lang="en" class="list-disc space-y-2 pl-5 text-sm leading-6 text-muted"></ul><button type="button" id="new-cue" class="mt-5 ${s.secondary}">Next cue card ${icon('arrow')}</button></div>${timer('ielts')}</div></div></section>`;

export const course = (exam) => {
  const isIelts = exam === 'IELTS';
  return {
    page: isIelts ? 'ielts' : 'sat',
    title: isIelts ? 'IELTS lessons & personal coaching' : 'SAT Reading & Writing lessons',
    description: `Try four original ${exam} mini-lessons, practise with feedback and build a personal study plan with L.B. English Co.`,
    body: `<section class="${s.wrap} pb-12 pt-10"><nav aria-label="Breadcrumb" class="mb-9 flex items-center gap-3 text-xs font-medium text-muted"><a href="index.html">Home</a><span aria-hidden="true">/</span><span>${exam} lessons</span></nav><div class="grid items-center gap-10 lg:grid-cols-[1.25fr_0.8fr]"><div>${eyebrow(isIelts?'IELTS / Your band. Your next chapter.':'SAT / Reading & Writing, with purpose.')}<h1 class="max-w-3xl text-5xl font-semibold leading-[1.08] tracking-[-0.055em] sm:text-6xl lg:text-7xl">${isIelts?'The English you need.<br>The progress you<br>can explain.':'Read with purpose.<br>Answer with<br>confidence.'}</h1><p class="my-7 max-w-xl text-base leading-8 text-muted">${isIelts?'Build the skills behind your IELTS goal with purposeful lessons, specific feedback and a study routine that fits your life.':'Make evidence, language and pacing work together. Build a repeatable approach to Digital SAT Reading & Writing, one decision at a time.'}</p><div class="flex flex-wrap gap-3">${link('Try a free mini-lesson','#lessons')}${button('Build my study plan',`data-open="planner" data-goal="${exam}"`,true)}</div></div>
      <aside class="rounded-[2rem] ${isIelts?'bg-lime/60':'bg-lilac'} p-8"><div class="mb-10 flex items-center justify-between"><span class="text-5xl font-semibold tracking-tighter">${exam}</span>${icon('diagonal','h-10 w-10')}</div><p class="mb-5 text-xs font-bold uppercase tracking-widest">A route built around you</p><ul class="space-y-4 text-sm">${(isIelts?['Four skills, connected by one clear plan','Academic and General Training coaching routes','Private 1:1 or a VIP group of 3–5','Four original free mini-lessons']:['Reading & Writing coaching only','Four content domains, purposeful practice','Private 1:1 or a VIP group of 3–5','Four original free mini-lessons']).map(text=>`<li class="flex gap-3">${icon('check','h-4 w-4 mt-0.5')}${text}</li>`).join('')}</ul><div class="mt-7 border-t border-ink/20 pt-5 text-xs leading-6">${isIelts?'Know your current skills. Choose what to work on next.':'The SAT also includes Math. This course focuses on Reading & Writing.'}</div></aside></div></section>
      <nav class="border-y border-line" aria-label="Course sections"><div class="${s.wrap} flex flex-wrap gap-x-6 gap-y-1 py-3 text-sm font-semibold"><a class="py-3" href="#lessons">Free mini-lessons</a><a class="py-3" href="#curriculum">The learning route</a>${isIelts?'<a class="py-3" href="#essay-planner">Essay planner</a>':''}<a class="py-3" href="#${isIelts?'calculator':'pacing'}">${isIelts?'Band calculator':'Pacing practice'}</a><a class="py-3" href="resources.html?exam=${exam}">Free ${exam} resources ↗</a></div></nav>
      <section id="lessons" class="${s.wrap} py-20"><div class="mb-10 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div>${eyebrow('Try the way we teach')}<h2 class="${s.heading}">One useful idea.<br>Then make it yours.</h2></div><p class="text-sm font-semibold" id="course-progress" data-exam="${exam}">0 of 4 mini-lessons completed</p></div><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">${lessonCards(exam)}</div><p class="mt-5 text-xs leading-6 text-muted">Original practice previews with explanations. Completion is saved on this device. These activities are not official exam questions or full courses.</p></section>
      <section id="curriculum" class="bg-white"><div class="${s.wrap} py-20"><div class="mb-10 grid gap-6 md:grid-cols-2"><div>${eyebrow('The learning route')}<h2 class="${s.heading}">Go beyond the answer.</h2></div><p class="self-end text-sm leading-7 text-muted">Start by understanding the task, practise with intention, then review the decisions you made. A tutor can adapt the sequence and depth to your current work.</p></div><div class="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">${lessons[exam].map((l,i)=>`<div class="border-t border-line pt-5"><span class="text-xs font-bold text-muted">0${i+1}</span><h3 class="my-4 text-xl font-semibold tracking-tight">${l.skill}</h3><p class="text-sm leading-7 text-muted">${l.transfer}</p></div>`).join('')}</div></div></section>
      <div class="h-20" aria-hidden="true"></div>
      ${isIelts?essayPlanner()+bandCalculator():`<section id="pacing" class="${s.wrap} grid gap-10 pb-20 lg:grid-cols-2"><div>${eyebrow('Make room for careful decisions')}<h2 class="${s.heading}">Practise your pace.<br>Review your choices.</h2><p class="my-5 text-sm leading-7 text-muted">The standard Digital SAT Reading &amp; Writing section has 54 questions across two 32-minute modules. Use this timer with your own practice set, then log what cost you time. This timer does not simulate adaptive testing.</p><a class="text-xs font-semibold underline underline-offset-4" href="https://satsuite.collegeboard.org/sat/whats-on-the-test/structure" target="_blank" rel="noopener">See the official SAT structure ↗</a><div class="mt-7">${link('Open the SAT pacing map','resources.html?resource=sat-pacing',true)}</div></div>${timer('sat',1920)}</section>`}
      ${isIelts?speakingDrill():''}
      <section class="${s.wrap} py-20"><div class="flex flex-col justify-between gap-7 rounded-3xl bg-ink p-8 text-white md:flex-row md:items-center sm:p-12"><div><h2 class="text-3xl font-semibold tracking-tight">Make the next step personal.</h2><p class="mt-3 text-sm leading-7 text-white/70">Bring your goal, your timeline and the parts you find difficult.</p></div><button type="button" data-open="consultation" data-goal="${exam}" class="inline-flex min-h-12 shrink-0 items-center justify-center gap-3 rounded-full bg-lime px-6 py-3 text-sm font-bold text-ink">Prepare my coaching brief ${icon('arrow')}</button></div></section>`
  };
};
