import { styles as s, icon, link, button, eyebrow } from '../ui.js';
import { lessons } from '../lessons.js';
import { exams } from '../exams.js';

export const lessonCards = (exam) => lessons[exam].map((lesson, index) => `<article class="flex flex-col rounded-2xl border border-line bg-white p-6"><div class="flex justify-between gap-3 text-[11px] font-bold uppercase tracking-wider text-muted"><span>0${index+1} / ${lesson.skill}</span><span class="whitespace-nowrap">${lesson.duration}</span></div><h3 class="mb-4 mt-6 text-xl font-semibold leading-7 tracking-tight">${lesson.title}</h3><p class="mb-6 text-sm leading-6 text-muted">${lesson.concept.split('. ')[0]}.</p><button type="button" data-lesson="${lesson.id}" class="mt-auto flex min-h-12 items-center justify-between border-t border-line pt-4 text-sm font-bold"><span data-lesson-label="${lesson.id}">Open mini-lesson</span>${icon('arrow')}</button></article>`).join('');

import { timer } from '../components.js';
export { timer } from '../components.js';

const essayPlanner = () => `<section id="essay-planner" class="${s.wrap} pb-20"><div class="grid gap-10 lg:grid-cols-2"><div>${eyebrow("Build an argument readers can follow")}<h2 class="${s.heading}">Plan with purpose.<br>Write with control.</h2><p class="my-5 text-sm leading-7 text-muted">Choose a Task 2 question type. Build an outline around the actual prompt, with reasons you can explain and examples that support them. The suggested four-part structure is a starting point, not a fixed exam requirement.</p><label for="essay-type" class="${s.label}">Question type<select id="essay-type" class="${s.input}"><option value="opinion">Agree or disagree</option><option value="discussion">Discuss both views</option><option value="problem">Causes and solutions</option><option value="advantages">Advantages outweigh disadvantages</option></select></label><p id="essay-prompt" data-practice lang="en" class="mt-5 rounded-2xl bg-lime/30 p-5 text-sm font-semibold leading-7"></p></div><div><div id="essay-outline" class="space-y-5"></div><p id="essay-status" role="status" class="my-4 text-xs leading-6 text-muted"></p><button type="button" id="download-essay" class="${s.secondary}">Download my outline ${icon("diagonal")}</button></div></div></section>`;

const bandCalculator = () => `<section id="calculator" class="${s.wrap} grid gap-10 pb-20 lg:grid-cols-2"><div>${eyebrow('Read your four signals')}<h2 class="${s.heading}">See what your<br>next band needs.</h2><p class="my-5 max-w-lg text-sm leading-7 text-muted">Enter four component scores to see the rounded average. This calculator does not assess your English or determine whether you meet an institution’s requirements.</p><a href="https://ielts.org/take-a-test/your-results/ielts-scoring-in-detail" class="text-xs font-semibold underline underline-offset-4" target="_blank" rel="noopener">How IELTS calculates the overall band ↗</a></div>
  <div class="rounded-3xl bg-lime/40 p-7"><div class="mb-6 flex items-center justify-between border-b border-ink/20 pb-6"><span class="text-sm font-semibold">Calculated overall band</span><output id="overall-band" aria-live="polite" class="text-5xl font-semibold tracking-tight">7.5</output></div>
  ${[['Listening',7.5],['Reading',8],['Writing',7],['Speaking',7.5]].map(([name,value])=>`<div class="mb-5"><label for="band-${name.toLowerCase()}" class="mb-2 flex justify-between text-sm font-semibold">${name}<output id="value-${name.toLowerCase()}">${value.toFixed(1)}</output></label><input id="band-${name.toLowerCase()}" data-band="${name.toLowerCase()}" type="range" min="0" max="9" step="0.5" value="${value}" class="h-8 w-full accent-ink"></div>`).join('')}</div></section>`;

const speakingDrill = () => `<section id="cue-simulator" class="bg-white"><div class="${s.wrap} grid gap-10 py-20 lg:grid-cols-[1fr_0.85fr]"><div>${eyebrow('Put your learning into words')}<h2 class="${s.heading}">Your next speaking<br>win starts here.</h2><p class="mt-5 max-w-lg text-sm leading-7 text-muted">Draw an original cue card. Use a minute to prepare, then switch to two minutes for your response. The timer does not record audio.</p><a href="speaking.html" class="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-bold">Explore the speaking studio ${icon('arrow')}</a></div><div><div class="mb-4 rounded-2xl bg-paper p-6"><p id="cue-category" class="text-xs font-semibold text-muted"></p><h3 id="cue-topic" data-practice lang="en" class="my-4 text-xl font-bold leading-7">Describe an electronic device that you find indispensable.</h3><ul id="cue-points" data-practice lang="en" class="list-disc space-y-2 pl-5 text-sm leading-6 text-muted"></ul><button type="button" id="new-cue" class="mt-5 ${s.secondary}">Next cue card ${icon('arrow')}</button></div>${timer('ielts')}</div></div></section>`;
const ydtCalculator = () => `<section id="ydt-net" class="${s.wrap} grid gap-8 pb-20 lg:grid-cols-[.9fr_1.1fr]"><div>${eyebrow('YDT practice, made measurable')}<h2 class="${s.heading}">See the value of every decision.</h2><p class="my-5 text-sm leading-7 text-muted">Practice estimate: correct − incorrect / 4. This is not a YKS placement score or ranking prediction.</p></div><div class="rounded-3xl bg-lilac p-7"><div class="grid gap-4 sm:grid-cols-2"><label class="${s.label}">Correct<input id="ydt-correct" class="${s.input}" type="number" min="0" max="80" value="74"></label><label class="${s.label}">Incorrect<input id="ydt-wrong" class="${s.input}" type="number" min="0" max="80" value="6"></label></div><p id="ydt-net-error" class="mt-3 text-sm font-semibold" role="status"></p><p class="mt-5 text-xs font-bold uppercase tracking-widest text-muted">Practice net</p><output id="ydt-net-result" class="mt-2 block text-5xl font-semibold tracking-tight" aria-live="polite">72.50</output></div></section>`;

export const course = (exam) => {
  const meta = exams[exam];
  if (!meta) throw new Error(`Unknown exam: ${exam}`);
  const isIelts = exam === 'IELTS';
  const isSat = exam === 'SAT';
  const isNational = meta.family === 'turkiye';
  const lessonCount = lessons[exam].length;
  return {
    page: meta.slug,
    title: isIelts ? 'IELTS lessons & personal coaching' : `${meta.label} lessons & personal coaching`,
    description: meta.description,
    body: `<section class="${s.wrap} pb-12 pt-10"><nav aria-label="Breadcrumb" class="mb-9 flex flex-wrap items-center gap-3 text-xs font-medium text-muted"><a href="index.html">Home</a><span aria-hidden="true">/</span><a href="${meta.family === 'international' ? 'international-exams.html' : 'turkiye-exams.html'}">${meta.family === 'international' ? 'International exams' : 'Türkiye exams'}</a><span aria-hidden="true">/</span><span>${meta.label}</span></nav><div class="grid items-center gap-10 lg:grid-cols-[1.25fr_0.8fr]"><div>${eyebrow(meta.label+' / '+(isSat?'Reading & Writing only':meta.family === 'turkiye'?'English language preparation':'Your next useful improvement'))}<h1 class="max-w-3xl text-5xl font-semibold leading-[1.08] tracking-[-0.055em] sm:text-6xl lg:text-7xl">${isIelts?'The English you need.<br>The progress you<br>can explain.':isSat?'Read with purpose.<br>Answer with<br>confidence.':meta.title}</h1><p class="my-7 max-w-xl text-base leading-8 text-muted">${meta.description}</p><div class="flex flex-wrap gap-3">${link('Try a free starter','#lessons')}${button('Build my study plan',`data-open="planner" data-goal="${exam}"`,true)}</div></div>
      <aside class="rounded-[2rem] ${meta.color==='lime'?'bg-lime/60':meta.color==='peach'?'bg-peach':'bg-lilac'} p-8"><div class="mb-10 flex items-center justify-between"><span class="text-5xl font-semibold tracking-tighter">${meta.label}</span>${icon('diagonal','h-10 w-10')}</div><p class="mb-5 text-xs font-bold uppercase tracking-widest">A plan built around your result</p><ul class="space-y-4 text-sm"><li class="flex gap-3">${icon('check','h-4 w-4 mt-0.5')}${meta.skills}</li><li class="flex gap-3">${icon('check','h-4 w-4 mt-0.5')}${isSat?'Reading & Writing coaching only':isNational?'English-language practice with the exam’s own purpose in view':exam==='TOEFL'?'Current-format starter practice':'Current-format coaching and original practice'}</li><li class="flex gap-3">${icon('check','h-4 w-4 mt-0.5')}${lessonCount} original free starter lessons</li><li class="flex gap-3">${icon('check','h-4 w-4 mt-0.5')}${meta.tool}</li></ul><div class="mt-7 border-t border-ink/20 pt-5 text-xs leading-6">${isSat?'The full SAT also includes Math. This course focuses on Reading & Writing.':isNational?'Practice feedback is for this activity; it is not an official score or placement result.':'Build a realistic route from your current work to your goal.'}</div></aside></div></section>
      <nav class="border-y border-line" aria-label="Course sections"><div class="${s.wrap} flex flex-wrap gap-x-6 gap-y-1 py-3 text-sm font-semibold"><a class="py-3" href="#lessons">Starter practice</a><a class="py-3" href="#curriculum">How progress compounds</a>${isIelts?'<a class="py-3" href="#essay-planner">Essay planner</a>':''}${isIelts?'<a class="py-3" href="#calculator">Band calculator</a>':isSat?'<a class="py-3" href="#pacing">Pacing practice</a>':''}<a class="py-3" href="resources.html?exam=${exam}">Free ${meta.label} resources ↗</a></div></nav>
      <section id="lessons" class="${s.wrap} py-20"><div class="mb-10 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div>${eyebrow('See the method in action')}<h2 class="${s.heading}">Learn the move.<br>Use it with confidence.</h2></div><p class="text-sm font-semibold" id="course-progress" data-exam="${exam}">0 of ${lessonCount} starter lessons completed</p></div><div class="grid gap-4 sm:grid-cols-2 ${lessonCount>2?'lg:grid-cols-4':'lg:grid-cols-2'}">${lessonCards(exam)}</div><p class="mt-5 text-xs leading-6 text-muted">Original practice previews with explanations. Completion is saved on this device. These activities are not official exam questions or full courses.</p></section>
      <section id="curriculum" class="bg-white"><div class="${s.wrap} py-20"><div class="mb-10 grid gap-6 md:grid-cols-2"><div>${eyebrow('How progress compounds')}<h2 class="${s.heading}">Turn practice into progress.</h2></div><p class="self-end text-sm leading-7 text-muted">Understand the task, practise with intention, then review the decisions you made. That is how a short lesson becomes a stronger week.</p></div><div class="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">${lessons[exam].map((l,i)=>`<div class="border-t border-line pt-5"><span class="text-xs font-bold text-muted">0${i+1}</span><h3 class="my-4 text-xl font-semibold tracking-tight">${l.skill}</h3><p class="text-sm leading-7 text-muted">${l.transfer}</p></div>`).join('')}</div></div></section>
      <div class="h-20" aria-hidden="true"></div>
      ${isIelts?essayPlanner()+bandCalculator():isSat?`<section id="pacing" class="${s.wrap} grid gap-10 pb-20 lg:grid-cols-2"><div>${eyebrow('Protect the time that matters')}<h2 class="${s.heading}">Protect your time.<br>Improve your decisions.</h2><p class="my-5 text-sm leading-7 text-muted">Use this timer with your own Digital SAT Reading &amp; Writing practice set, then log what cost you time. This timer does not simulate adaptive testing.</p><a class="text-xs font-semibold underline underline-offset-4" href="https://satsuite.collegeboard.org/sat/whats-on-the-test/structure" target="_blank" rel="noopener">See the official SAT structure ↗</a><div class="mt-7">${link('Open the SAT pacing map','resources.html?resource=sat-pacing',true)}</div></div>${timer('sat',1920)}</section>`:`<section class="${s.wrap} grid gap-8 pb-20 lg:grid-cols-[1fr_0.8fr]"><div>${eyebrow('Your next best move')}<h2 class="${s.heading}">Train the decisions that move your result.</h2><p class="my-5 max-w-xl text-sm leading-7 text-muted">Start with one focused lesson, keep the insight and build a weekly rhythm you can sustain. This is practice guidance, not an official result.</p>${link('Open the free resource library',`resources.html?exam=${exam}`,true)}</div><div class="rounded-3xl bg-paper p-7"><p class="text-xs font-bold uppercase tracking-widest text-muted">This week’s focus</p><p class="mt-4 text-xl font-semibold">${meta.skills}</p><p class="mt-4 text-sm leading-7 text-muted">${isNational?'YDT, YDS and YÖKDİL have different purposes. Choose the page that matches your requirement.':exam==='TOEFL'?'Current TOEFL iBT tasks: Build a Sentence, Write an Email, Write for an Academic Discussion, Listen and Repeat, and Take an Interview. These two starters open the route; use official specifications for the complete task set.':'Use current-format TOEFL practice and review your response decisions.'}</p></div></section>${exam==='YDT'?ydtCalculator():''}`}
      ${isIelts?speakingDrill():''}
      <section class="${s.wrap} py-20"><div class="flex flex-col justify-between gap-7 rounded-3xl bg-ink p-8 text-white md:flex-row md:items-center sm:p-12"><div><h2 class="text-3xl font-semibold tracking-tight">Make your next result personal.</h2><p class="mt-3 text-sm leading-7 text-white/70">Bring the goal, the deadline and the part that keeps slowing you down.</p></div><button type="button" data-open="consultation" data-goal="${exam}" class="inline-flex min-h-12 shrink-0 items-center justify-center gap-3 rounded-full bg-lime px-6 py-3 text-sm font-bold text-ink">Prepare my coaching brief ${icon('arrow')}</button></div></section>`
  };
};
