import { styles as s, icon, link, button, eyebrow } from '../ui.js';
import { exams, familyMeta, familyExamIds } from '../exams.js';

const hub = (family) => {
  const meta = familyMeta[family];
  const ids = familyExamIds(family);
  const cards = ids.map((id) => {
    const exam = exams[id];
    return `<article class="group flex flex-col rounded-[2rem] border border-line ${exam.color==='lime'?'bg-lime/55':exam.color==='peach'?'bg-peach':'bg-lilac'} p-7 sm:p-9"><div class="flex items-center justify-between gap-4"><span class="rounded-full border border-ink/25 px-4 py-1.5 text-xs font-bold tracking-[.14em]">${exam.label}</span><span class="text-xs font-semibold">${exam.family==='turkiye'?'ENGLISH PREPARATION':'ONLINE COACHING'}</span></div><h2 class="mt-8 text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">${exam.title}</h2><p class="mt-4 text-sm leading-7 text-muted">${exam.description}</p><p class="mt-6 border-t border-ink/20 pt-5 text-xs font-semibold">${exam.skills}</p><a class="mt-7 flex min-h-12 items-center justify-between text-sm font-bold" href="${exam.route}">Open ${exam.label} route <span class="grid h-10 w-10 place-items-center rounded-full bg-ink text-white">${icon('arrow')}</span></a></article>`;
  }).join('');
  return { page: family==='international'?'international-exams':'turkiye-exams', title:family==='international'?'English coaching for international outcomes':'English preparation for Türkiye outcomes', description:meta.intro, body:`<section class="${s.wrap} pb-14 pt-14"><nav aria-label="Breadcrumb" class="mb-9 flex items-center gap-3 text-xs font-medium text-muted"><a href="index.html">Home</a><span aria-hidden="true">/</span><span>${meta.label}</span></nav>${eyebrow(meta.label)}<h1 class="mt-5 max-w-4xl text-5xl font-semibold leading-[1.03] tracking-[-.06em] sm:text-7xl">Build the English for the outcome ahead.</h1><p class="mt-7 max-w-2xl text-base leading-8 text-muted">${family==='international'?'Build practical English for study, work and global mobility, then add the international exam route that supports your next decision.':'Build practical English for study, work and academic life in Türkiye, then add the exam route that matches your requirement.'}</p><div class="mt-8 flex flex-wrap gap-3">${button('Help me choose','data-open="finder"')}${link('Build a study plan','#compare',true)}</div></section><section id="compare" class="${s.wrap} grid gap-5 pb-20 md:grid-cols-3">${cards}</section><section class="bg-white"><div class="${s.wrap} grid gap-8 py-16 md:grid-cols-[.8fr_1.2fr]"><div>${eyebrow('Why the route matters')}<h2 class="${s.heading}">${family==='international'?'Match the test to the decision ahead.':'Start with the requirement, then build the route.'}</h2></div><p class="text-sm leading-8 text-muted">${family==='international'?'IELTS and TOEFL help you prove English readiness for study and other goals. SAT is the college-readiness and admission route; this studio sharpens its Reading & Writing section. Start with English, then choose the score route that earns its place.':'YDT supports university entry through YKS. YDS serves academic and public-service requirements. YÖKDİL is the academic route, with Fen, Sağlık and Sosyal Bilimleri fields. Start with the English you need, then choose the exam that matches your next decision.'}</p></div></section>`};
};
export const international = () => hub('international');
export const turkiye = () => hub('turkiye');
