import { styles as s, icon, eyebrow, button } from '../ui.js';
import { resources } from '../content.js';
import { escapeHtml as esc } from '../lib/core.js';

export const resourceCard = (r) => `<article data-resource-card="${r.id}" class="flex flex-col rounded-2xl border border-line bg-white p-6"><div class="mb-6 flex items-center justify-between gap-2"><span class="rounded-full bg-paper px-3 py-2 text-[10px] font-bold uppercase tracking-wider">${esc(r.exam)}</span><button type="button" data-save="${r.id}" aria-pressed="false" aria-label="Save ${esc(r.title)}" class="grid h-11 w-11 place-items-center rounded-full border border-line aria-pressed:bg-lime">${icon('star','h-4 w-4')}</button></div><span class="text-[10px] font-semibold uppercase tracking-widest text-muted">${esc(r.type==='web'?'Interactive tool':r.type==='doc'?'Editable notes':'Printable worksheet')}</span><h3 class="mb-3 mt-3 text-xl font-semibold tracking-tight">${esc(r.title)}</h3><p class="mb-6 text-sm leading-7 text-muted">${esc(r.description)}</p><button type="button" data-resource="${r.id}" class="mt-auto flex min-h-12 items-center justify-between border-t border-line pt-4 text-sm font-bold">Use this resource ${icon('arrow')}</button></article>`;

export const library = () => ({
  page:'resources', title:'Free English & exam resource library', description:'Eight useful English learning tools: IELTS writing checklist, SAT pacing map, speaking practice, editable notes and planners.',
  body:`<section class="${s.wrap} pb-12 pt-14">${eyebrow('Open access. Practical by design.')}<div class="grid gap-6 md:grid-cols-2"><h1 class="text-5xl font-semibold leading-[1.08] tracking-[-0.05em] sm:text-6xl">Good tools.<br>Better study days.</h1><div class="self-end"><p class="max-w-lg text-base leading-8 text-muted">Eight focused resources to help you notice, practise and reflect. Add notes, tick off your progress and keep the useful parts.</p><p class="mt-4 text-xs font-semibold text-muted">Free to use · No account needed · Saved on this device</p></div></div></section>
  <section id="library" class="${s.wrap} pb-20">
    <div class="mb-8 rounded-2xl border border-line bg-white p-5 sm:p-6">
      <label for="resource-search" class="text-sm font-bold">Find your next useful resource</label><div class="relative mt-3">${icon('search','absolute left-4 top-4 h-5 w-5 text-muted')}<input id="resource-search" type="search" placeholder="Try writing, SAT, vocabulary…" class="${s.input} pl-12"></div>
      <div class="mt-5 flex flex-wrap gap-2" aria-label="Filter by learning goal">${['All','IELTS','SAT','Speaking','Saved'].map((name,index)=>`<button type="button" data-filter="${name}" aria-pressed="${index===0}" class="${s.chip}">${name==='All'?'All resources':name==='Saved'?'Saved resources':name}</button>`).join('')}</div>
      <div class="mt-5 flex flex-wrap items-center justify-between gap-3"><label class="text-xs font-semibold">Resource type <select id="resource-type" class="ml-2 rounded-lg border border-line p-2.5 text-sm"><option value="all">All types</option><option value="web">Web tools</option><option value="doc">Editable notes</option><option value="template">Templates</option><option value="pdf">Print / PDF</option></select></label><button type="button" id="clear-filters" class="min-h-11 text-xs font-semibold underline underline-offset-4">Clear filters</button></div>
    </div>
    <p id="resource-count" class="mb-5 text-sm font-semibold text-muted" role="status">8 free resources</p>
    <div id="resource-grid" class="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">${resources.map(resourceCard).join('')}</div>
    <div id="resource-empty" hidden class="rounded-2xl border border-dashed border-line px-8 py-16 text-center"><h2 class="text-xl font-bold">No resources match just yet.</h2><p class="my-4 text-sm text-muted">Try a different search or clear your filters. Save a resource with the star to find it here later.</p><button type="button" data-clear-filters class="${s.secondary}">Show all resources</button></div>
  </section>
  <section id="interactive-tools" class="border-t border-line bg-white"><div class="${s.wrap} grid gap-8 py-16 md:grid-cols-2"><div>${eyebrow('Put the tools to work')}<h2 class="text-3xl font-semibold tracking-tight">Give your week a clear focus.</h2><p class="my-5 text-sm leading-7 text-muted">Build a plan for IELTS, SAT, speaking or another English goal. Every suggested session fits the weekly hours you choose.</p>${button('Build my study plan')}</div><div class="rounded-2xl bg-paper p-7"><h3 class="text-xl font-semibold">A practice check, with useful feedback.</h3><p class="my-5 text-sm leading-7 text-muted">Try eight questions on grammar and vocabulary. Review each answer and use it to choose what to practise next.</p>${button('Try the language check','data-open="diagnostic"',true)}<p class="mt-4 text-xs leading-6 text-muted">This activity does not estimate exam scores or CEFR equivalencies.</p></div></div></section>`
});
