import { styles as s, icon, eyebrow, button, link } from '../ui.js';
import { timer } from './courses.mjs';

export const speaking = () => ({
  page:'speaking', title:'Speaking coaching for real conversations', description:'Practise clear answers, rehearse high-stakes conversations and build confidence with focused speaking coaching.',
  body:`<section class="${s.wrap} grid gap-10 py-16 lg:grid-cols-2"><div>${eyebrow('Confidence, rehearsed')}<h1 class="text-5xl font-semibold leading-[1.1] tracking-[-0.055em] sm:text-6xl">Speak with more ease.<br>Show what you know.</h1><p class="my-6 text-base leading-8 text-muted">Turn ideas into clear answers, practise the moments that matter and get feedback you can use immediately.</p><div class="flex flex-wrap gap-3">${link('Try a speaking prompt','#topic-simulator')}${button('Plan my speaking practice','data-open="planner" data-goal="Speaking"',true)}</div></div><div class="rounded-3xl bg-peach p-9"><span class="text-xs font-bold uppercase tracking-widest">Your voice, ready for real life</span><h2 class="my-6 text-3xl font-semibold tracking-tight">Sound natural.<br>Think clearly.</h2><ul class="space-y-4 text-sm leading-6"><li>01 / Make your point and give it shape.</li><li>02 / Rehearse the conversation that matters.</li><li>03 / Notice the difference, then try again.</li></ul></div></section>
  <section id="topic-simulator" class="bg-white"><div class="${s.wrap} grid gap-9 py-16 lg:grid-cols-[1.2fr_0.8fr]"><div>${eyebrow('One prompt. One minute. New confidence.')}<p id="prompt-category" class="text-xs font-semibold text-muted"></p><h2 id="prompt-title" data-practice lang="en" class="my-5 text-3xl font-semibold leading-tight tracking-tight"></h2><p id="prompt-description" data-practice lang="en" class="mb-6 text-sm leading-7 text-muted"></p><div id="prompt-tags" data-practice lang="en" class="mb-7 flex flex-wrap gap-2"></div><button id="next-prompt" type="button" class="${s.secondary}">Next conversation topic ${icon('arrow')}</button><p class="mt-5 text-xs leading-6 text-muted">Use the language that serves your meaning. These prompts stretch your thinking; simplify whenever clarity matters more.</p></div><div>${timer('speaking',120)}<p class="mt-4 text-xs leading-6 text-muted">A private countdown for your practice. No audio is recorded or uploaded.</p></div></div></section>
  <section id="pricing" class="${s.wrap} grid gap-6 py-20 md:grid-cols-3">${[['A speaking circle that keeps you moving','A group of 3–5, matched by level and learning goals.','VIP group of 3–5'],['Private coaching, built around you','Private practice, individual feedback and space for your priorities.','Private 1:1'],['High-stakes conversation practice','Rehearse a specific situation and refine your message.','Private 1:1']].map(([title,desc,format])=>`<article class="rounded-2xl border border-line p-7"><h2 class="text-xl font-semibold">${title}</h2><p class="my-5 text-sm leading-7 text-muted">${desc}</p>${button('Build my coaching brief',`data-open="consultation" data-goal="Speaking" data-format="${format}"`,true)}</article>`).join('')}</section>
  <section class="${s.wrap} pb-20">${link('Get the 7-day speaking reset','resources.html?resource=speaking-reset',true)}</section>`
});

export const national = () => ({
  page:'ydt-yds', lang:'tr', title:'YDT, YDS ve YÖKDİL çalışma stüdyosu', description:'Kelime kartları, okuma stratejileri ve kişisel çalışma planıyla YDT, YDS ve YÖKDİL hazırlığı.',
  body:`<section class="${s.wrap} grid gap-10 py-16 lg:grid-cols-2"><div>${eyebrow('YDT · YDS · YÖKDİL')}<h1 class="text-5xl font-semibold leading-[1.1] tracking-[-0.045em] sm:text-6xl">Ezberin ötesine geç.<br>Kararını gerekçelendir.</h1><p class="my-6 text-base leading-8 text-muted">Kelimeyi bağlamda öğren. Cümlenin yapısını çöz. Cevabını metindeki kanıtla destekle. Çalışmanı hedefin ve ayırabildiğin zaman etrafında planla.</p><div class="flex flex-wrap gap-3">${button('Çalışma planımı oluştur','data-open="planner" data-goal="YDT"')}${link('Kelime pratiğine başla','#kelime-drilli',true)}</div></div><div id="net-hesaplama" class="rounded-3xl bg-lilac p-8"><h2 class="text-xl font-bold">YDT net hesabı</h2><p class="my-4 text-sm leading-7">Alıştırma hesabı: doğru − yanlış / 4. Bu araç yerleştirme puanı veya sıralama tahmini yapmaz.</p><div class="grid grid-cols-2 gap-4"><label class="${s.label}">Doğru<input id="correct-count" class="${s.input}" type="number" min="0" max="80" step="1" value="74"></label><label class="${s.label}">Yanlış<input id="wrong-count" class="${s.input}" type="number" min="0" max="80" step="1" value="6"></label></div><p id="net-error" class="mt-3 text-sm font-semibold" role="status"></p><p class="mt-6 text-sm font-semibold">Hesaplanan net</p><output id="net-result" class="mt-2 block text-5xl font-semibold tracking-tight" aria-live="polite">72.50</output></div></section>
  <section id="kelime-drilli" class="bg-white"><div class="${s.wrap} grid gap-10 py-16 lg:grid-cols-2"><div>${eyebrow('Bağlamla hatırla')}<h2 class="${s.heading}">Bir kelime.<br>Yeni bir bağlantı.</h2><p class="my-5 text-sm leading-7 text-muted">Önce anlamı hatırlamayı dene. Kartı açtıktan sonra kelimeyi kendi cümlende kullan. Hatalarını kelime defterine kaydet.</p>${link('Kelime hata defterini aç','resources.html?resource=yds-log',true)}</div><div class="rounded-3xl bg-paper p-8"><p id="vocab-type" class="text-xs font-bold uppercase tracking-wider text-muted"></p><h3 id="vocab-word" data-practice lang="en" class="my-6 text-4xl font-semibold tracking-tight"></h3><div id="vocab-answer" hidden><p id="vocab-meaning" class="font-semibold"></p><p id="vocab-sample" data-practice lang="en" class="my-4 text-sm italic leading-7 text-muted"></p></div><div class="mt-7 flex flex-wrap gap-3"><button id="reveal-word" type="button" aria-expanded="false" aria-controls="vocab-answer" class="${s.button}">Anlamı göster</button><button id="next-word" type="button" class="${s.secondary}">Sonraki kelime ${icon('arrow')}</button></div><p id="vocab-count" class="mt-4 text-xs text-muted"></p></div></div></section>
  <section class="${s.wrap} py-20">${eyebrow('Çalışmayı daha anlamlı kıl')}<div class="grid gap-5 md:grid-cols-3">${[['Cümle yapısı','Özne, yüklem ve bağlaç ilişkilerini belirle.'],['Metinde kanıt','Çıkarım yaparken metnin söylediği sınırlar içinde kal.'],['Hata analizi','Yanlış cevabın neden çekici geldiğini açıklayarak tekrar et.']].map(([a,b])=>`<article class="rounded-2xl border border-line p-7"><h2 class="text-xl font-semibold">${a}</h2><p class="my-4 text-sm leading-7 text-muted">${b}</p></article>`).join('')}</div><div class="mt-8">${button('Hedefimi ve çalışma tercihlerimi yaz','data-open="consultation" data-goal="YDT"')}</div></section>`
});

export const legal = () => ({
  page:'legal', title:'Privacy & service information', description:'How local learning progress, notes, downloads and service information work on the L.B. English Co. website.',
  body:`<section class="${s.wrap} pb-12 pt-16">${eyebrow('Clear information before commitment')}<h1 class="text-5xl font-semibold tracking-[-0.045em] sm:text-6xl">Privacy &amp; service information.</h1><p class="mt-6 max-w-2xl text-base leading-8 text-muted">A plain description of how this site works today. Online booking, enquiry delivery and payment are not currently available.</p></section>
  <div class="${s.wrap} grid gap-10 pb-20 lg:grid-cols-[240px_1fr]"><nav aria-label="Information sections" class="flex flex-wrap content-start gap-3 text-sm font-semibold lg:sticky lg:top-28 lg:flex-col lg:self-start">${[['operator','The studio'],['privacy','Your information'],['cookies','Browser storage'],['terms','Coaching & booking'],['digital-products','Resources & downloads'],['education-notice','Independent practice'],['accessibility','Accessibility']].map(([id,title])=>`<a href="#${id}" class="py-2 underline underline-offset-4">${title}</a>`).join('')}</nav><article class="max-w-3xl space-y-10">
  ${[
    ['operator','The studio','L.B. English Co. is the learning studio name shown on this site. Verified legal operator details and a customer contact channel have not yet been supplied. The site therefore does not accept bookings or payments.'],
    ['privacy','Your information stays with your practice','Lesson completion, study plans, saved resources, checklist progress and resource notes are stored in your browser. They are not sent to a tutor or server. The coaching brief is generated on your device as a downloadable text file; downloading it does not send an enquiry. Avoid adding sensitive personal information to notes or shared downloads.'],
    ['cookies','Browser storage, clearly explained','The site uses localStorage for learning preferences and progress. It does not load analytics, advertising trackers, external fonts or embedded social media. Your hosting provider may process ordinary request logs when the site is hosted. Browser site-data controls can remove your saved progress. If storage is blocked or full, you can still practise, but new progress may not survive a reload.'],
    ['terms','Coaching and booking','Private 1:1 teaching, VIP groups of 3–5 and exam consultancy are described as service options. Lesson dates, availability, prices, cancellation conditions and a verified booking channel must be provided before any booking can be confirmed. A downloaded coaching brief is only a document you can keep or share.'],
    ['digital-products','Resources and downloads','The nine resources and the mini-lessons on this site are free practice tools. A resource can be edited in your browser, downloaded as a text file, or printed using your browser’s Print / Save as PDF function. There is no paid checkout, premium delivery system or refund transaction on this site.'],
    ['education-notice','Independent practice and realistic expectations','The mini-lessons are original practice content. L.B. English Co. is not affiliated with or endorsed by IELTS, College Board or the other exam owners named here. The language practice check cannot establish an official level, score or equivalency. The IELTS calculator only averages and rounds entered scores. Coaching outcomes depend on the learner and are not guaranteed. SAT coaching on this site covers Reading & Writing, not Math.'],
    ['accessibility','Keyboard, screen and motion preferences','Navigation and learning controls use semantic links, buttons, form labels and native dialogs. Dialogs support Escape and keyboard focus containment. The layout adapts to smaller screens and honours reduced-motion preferences. Resource text can be downloaded for use in other reading tools.'],
  ].map(([id,title,copy])=>`<section id="${id}" class="border-b border-line pb-9"><h2 class="mb-4 text-2xl font-semibold tracking-tight">${title}</h2><p class="text-sm leading-8 text-muted">${copy}</p></section>`).join('')}
  <section id="sources"><h2 class="mb-4 text-2xl font-semibold tracking-tight">Official exam references</h2><p class="mb-4 text-sm leading-7 text-muted">Check current exam details directly with the exam owner.</p><div class="grid justify-items-start gap-4 text-sm font-semibold underline underline-offset-4"><a href="https://ielts.org/take-a-test/your-results/ielts-scoring-in-detail" target="_blank" rel="noopener">IELTS scoring information ↗</a><a href="https://satsuite.collegeboard.org/sat/whats-on-the-test/structure" target="_blank" rel="noopener">College Board: SAT structure ↗</a></div></section>
  </article></div>`
});
