// Original short practice lessons. These are previews, not official exam material.
export const lessons = {
  IELTS: [
    {
      id: 'ielts-position', skill: 'Writing', title: 'Make your position unmistakable', duration: '8 min',
      concept: 'An opinion essay needs a position that answers the precise question. A balanced position is possible, but the reader must know what you think and why.',
      example: 'Prompt: Some people think public transport should be free for everyone. To what extent do you agree or disagree?',
      question: 'Which opening gives a clear, qualified position that can guide the whole essay?',
      options: ['Public transport is a controversial topic with many advantages and disadvantages.', 'Although free travel could reduce car use, I support subsidised fares rather than universal free access because funding must remain reliable.', 'This essay will discuss public transport and provide a conclusion.', 'Public transport is used by many people in different countries around the world.'],
      answer: 1,
      explanation: 'The second opening states the extent of agreement and introduces a reason. The other openings announce a topic without answering the question.',
      transfer: 'Write your own two-sentence introduction. State your position, then identify a reason you can develop.',
    },
    {
      id: 'ielts-evidence', skill: 'Reading', title: 'Separate false from not given', duration: '6 min',
      concept: 'False means the passage contradicts the statement. Not Given means the passage does not supply enough information to decide. Do not fill the gap with outside knowledge.',
      example: 'A city library extended its opening hours in May. Staff recorded more evening visits in June than in April. The report did not examine visitors’ ages.',
      question: 'Statement: Most of the additional evening visitors were university students.',
      options: ['True', 'False', 'Not Given'],
      answer: 2,
      explanation: 'The passage reports a change in visits but gives no evidence about who made the additional visits. It neither confirms nor contradicts the statement.',
      transfer: 'List the words you would need to see in the passage before this statement could be True.',
    },
    {
      id: 'ielts-correction', skill: 'Listening', title: 'Notice a speaker’s correction', duration: '5 min',
      concept: 'A speaker may give an initial answer and then correct it. Use this transcript exercise to practise following the final decision before trying the same strategy with audio.',
      example: 'Transcript: “Let’s meet by the main entrance at quarter past six. Actually, the doors there close early. Use the side gate instead, and make it half past six so everyone can arrive.”',
      question: 'What are the final meeting arrangements?',
      options: ['Main entrance, 6:15', 'Side gate, 6:15', 'Main entrance, 6:30', 'Side gate, 6:30'],
      answer: 3,
      explanation: '“Actually” introduces two corrections: the side gate replaces the main entrance, and half past six replaces quarter past six. This is transcript analysis, not a listening score.',
      transfer: 'Note the correction signals. In your next audio practice, wait for the complete exchange before confirming an answer.',
    },
    {
      id: 'ielts-develop', skill: 'Speaking', title: 'Develop an answer naturally', duration: '7 min',
      concept: 'A useful spoken answer moves from a direct response to a reason and a concrete detail. Practise flexible development rather than memorising a script.',
      example: 'Question: Is there a place in your town where you like spending time?',
      question: 'Which answer is most clearly developed with a relevant personal detail?',
      options: ['I often go to the riverside park because it is quiet. Last Sunday, I took a book there and stayed until sunset.', 'Yes, I like a place very much and it is a place that I like.', 'The infrastructure of municipal leisure is a multifaceted phenomenon.', 'There are many places, such as parks, shops, schools, offices and streets.'],
      answer: 0,
      explanation: 'The first answer names the place, explains the preference, and makes it concrete. Complexity alone does not make an answer effective.',
      transfer: 'Speak about your own place for 60 seconds. Notice whether each extra detail helps the listener picture it.',
    },
  ],
  SAT: [
    {
      id: 'sat-inference', skill: 'Information & Ideas', title: 'Keep the inference within the evidence', duration: '7 min',
      concept: 'A supported inference must follow from the text. Reject answers that introduce a cause, comparison or certainty the passage does not establish.',
      example: 'Researchers found that one species of urban bird began singing earlier on streets illuminated throughout the night than on streets where lamps switched off at midnight. The researchers noted that traffic noise also differed between the two types of street.',
      question: 'Which conclusion is best supported by the text?',
      options: ['Artificial light is the only factor that changes when urban birds sing.', 'Birds on unlit streets never sing before sunrise.', 'The observations are consistent with an influence of night lighting, but another environmental difference complicates that interpretation.', 'Switching lamps off at midnight will restore the singing schedule of every urban bird species.'],
      answer: 2,
      explanation: 'The evidence shows an association and explicitly identifies a possible confounding factor. It does not isolate light as the cause or support universal claims.',
      transfer: 'Explain why “only” and “every” make two of the alternatives stronger than the evidence allows.',
    },
    {
      id: 'sat-context', skill: 'Craft & Structure', title: 'Read the context before the word', duration: '6 min',
      concept: 'Choose the meaning that fits the specific sentence. A familiar dictionary meaning may be wrong in context; predict the sense before comparing options.',
      example: 'Although the museum’s early reports praised the restoration, the newly discovered correspondence offers a more qualified assessment: several repairs were effective, but others permanently obscured original details.',
      question: 'As used in the text, “qualified” most nearly means',
      options: ['professionally certified.', 'limited by reservations.', 'completely favourable.', 'expressed in numerical terms.'],
      answer: 1,
      explanation: 'The assessment recognises successes but adds reservations about damage. The contrast after the colon rules out an entirely favourable or purely numerical reading.',
      transfer: 'Replace “qualified” with a short phrase of your own, then reread the sentence to check the meaning.',
    },
    {
      id: 'sat-boundaries', skill: 'Standard English Conventions', title: 'Find the sentence boundary', duration: '6 min',
      concept: 'Two independent clauses need an appropriate boundary. A conjunctive adverb such as “however” does not by itself join them; a semicolon can separate the clauses.',
      example: 'The team expected the pigment to fade quickly ____ however, after six months its colour remained unchanged.',
      question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
      options: [',', 'and', ': however,', ';'],
      answer: 3,
      explanation: 'Both sides contain an independent clause. A semicolon before “however” and the existing comma after it form a correct boundary. A comma alone creates a comma splice.',
      transfer: 'Identify the subject and verb of each independent clause before choosing punctuation.',
    },
    {
      id: 'sat-transitions', skill: 'Expression of Ideas', title: 'Name the relationship first', duration: '5 min',
      concept: 'Before choosing a transition, describe how the next sentence relates to the previous one: contrast, result, example or continuation.',
      example: 'The seed coating retained moisture during dry periods. ____ seedlings treated with the coating survived longer than untreated seedlings in the same soil.',
      question: 'Which choice completes the text with the most logical transition?',
      options: ['Consequently,', 'Nevertheless,', 'For comparison,', 'On the contrary,'],
      answer: 0,
      explanation: 'Longer survival is presented as a result of moisture retention. The other choices signal contrast or comparison rather than this cause-and-effect relationship.',
      transfer: 'Explain the relationship without using a transition word. Then see whether “as a result” fits.',
    },
  ],
  TOEFL: [
    { id:'toefl-purpose', skill:'Reading', title:'Read in daily life: purpose & detail', duration:'7 min', concept:'Short notices and messages reward a precise reading of purpose before details. Identify what the writer needs the reader to do, then select only details that support that purpose.', example:'Campus notice: “The north library entrance will close at 18:00 on Thursday for electrical work. Students may enter through the east doors until the usual 22:00 closing time.”', question:'What is the main purpose of the notice?', options:['To announce a permanent library closure.','To explain a temporary entrance change and the alternative route.','To invite students to an electrical workshop.','To compare two campus libraries.'], answer:1, explanation:'The notice gives a temporary reason, a time and an alternative entrance. It does not announce a permanent closure or an event.', transfer:'Read one real English notice today. State its purpose in one sentence and record two details that prove your answer.' },
    { id:'toefl-email', skill:'Writing', title:'Write an email: clear request, complete response', duration:'8 min', concept:'A useful email answers every instruction, makes the request easy to find and uses a tone appropriate to the relationship. Clear organisation matters more than decorative language.', example:'You missed a lab orientation. Email the coordinator to explain briefly, ask for the next available session and confirm what you should prepare.', question:'Which opening best sets up a complete response?', options:['I missed the orientation. Please tell me what to do next.','Dear Coordinator, I was ill and could not attend Tuesday’s lab orientation. Could you tell me the next available session and whether I should bring any forms?','I am writing this email because emails are important in academic life.','Give me the information immediately because I need it.'], answer:1, explanation:'The second opening gives a concise reason and makes both required requests explicit in a polite tone.', transfer:'Draft a four-sentence email that includes context, request one, request two and a courteous close.' },
  ],
  YDT: [
    { id:'ydt-connectors', skill:'Cümle tamamlama', title:'Cümle tamamlama: neden, sonuç ve karşıtlık', duration:'7 dk', concept:'Bağlaç seçmeden önce iki bölüm arasındaki anlam ilişkisini adlandırın. Neden, sonuç ve karşıtlık ilişkileri aynı kelime alanından gelen seçenekleri ayırır.', example:'The new policy reduced paper use; ________, staff needed more time to learn the digital system.', question:'Which connector best completes the sentence?', options:['therefore','however','because','in order to'], answer:1, explanation:'The second clause contrasts with the first: paper use fell, but the transition required extra training time.', transfer:'Bir YDT cümlesinde bağlaçları kapatın; önce ilişkiyi Türkçe adlandırın, sonra seçeneği işaretleyin.' },
    { id:'ydt-inference', skill:'Paragraf', title:'Paragrafta ana fikir ve çıkarım', duration:'7 dk', concept:'Ana fikir metnin bütününü kapsar. Çıkarım ise metindeki kanıttan çıkar, fakat metnin söylemediği kesinlikte yeni bir iddia eklemez.', example:'Urban gardens can reduce surface heat in densely built areas. Their effect depends on plant coverage, watering and the surrounding materials.', question:'Which inference is supported?', options:['Every urban garden eliminates heat.','Plant coverage is one condition affecting how much cooling a garden provides.','Watering is unnecessary once a garden is planted.','Urban gardens always cool nearby buildings equally.'], answer:1, explanation:'The passage explicitly names plant coverage as a condition. The other options turn a qualified relationship into an absolute claim.', transfer:'Bir paragraf sorusunda “her zaman” ve “asla” gibi kesinlik bildiren kelimeleri kanıtla karşılaştırın.' },
  ],
  YDS: [
    { id:'yds-syntax', skill:'Cümle çözümleme', title:'Uzun cümleyi çözümleme', duration:'7 dk', concept:'Önce ana cümlenin özne ve yüklemini bulun. Ardından sıfat cümlecikleri, ara ifadeler ve bağlaçlarla kurulan mantıksal ilişkileri ayrı ayrı okuyun.', example:'Although the initial survey was limited, the researchers argue that the later longitudinal data provide a more reliable basis for comparison.', question:'What is the main claim?', options:['The initial survey was limited.','The later longitudinal data provide a more reliable basis for comparison.','The researchers stopped the survey.','Comparison was impossible.'], answer:1, explanation:'The although-clause supplies a concession; the main clause carries the researchers’ claim.', transfer:'Bir YDS cümlesini iki parçaya ayırın: ana iddia ve onu sınırlayan/ekleyen yan bilgi.' },
    { id:'yds-translation', skill:'Çeviri', title:'Çeviride anlam eşdeğerliği', duration:'8 dk', concept:'İyi çeviri yalnızca kelimeleri değil kapsamı, kipliği ve neden-sonuç ilişkisini korur. Daha güçlü veya daha kesin bir Türkçe ifade anlamı değiştirir.', example:'The findings may indicate a shift in consumer behaviour, but they do not establish a permanent trend.', question:'Which Turkish translation preserves the meaning?', options:['Bulgular tüketici davranışındaki değişimi kesin olarak kanıtlar.','Bulgular tüketici davranışında bir değişime işaret edebilir; ancak kalıcı bir eğilim ortaya koymaz.','Bulgular tüketici davranışını tamamen değiştirmiştir.','Bulgular kalıcı eğilimin nedenini açıklamaktadır.'], answer:1, explanation:'“May indicate” remains a possibility and “do not establish” keeps the limitation. The other choices add certainty or a different claim.', transfer:'Çevirinizde may, might, likely and must gibi kiplik işaretlerini ayrıca kontrol edin.' },
  ],
  YOKDIL: [
    { id:'yokdil-connectors', skill:'Akademik bağlaçlar', title:'Akademik bağlaçlar ve cümle tamamlama', duration:'7 dk', concept:'Akademik cümlede bağlaç, iki iddia arasındaki ilişkiyi taşır. Alan kelimeleri değişse de neden, karşıtlık ve sonuç mantığı aynı dikkatle okunur.', example:'The treatment reduced inflammation in the clinical sample; ________, the authors recommend further trials before routine use.', question:'Which connector best completes the academic sentence?', options:['nevertheless','because','for example','similarly'], answer:0, explanation:'The recommendation for further trials limits the apparent success of the first result, so nevertheless signals the contrast.', transfer:'Fen, sağlık veya sosyal bilimlerden kısa bir cümle seçin; bağlacı silip ilişkiyi önce kendi sözlerinizle açıklayın.' },
    { id:'yokdil-evidence', skill:'Akademik okuma', title:'Akademik paragrafta kanıt ve çıkarım', duration:'8 dk', concept:'Akademik metinlerde yöntem ve örnekler bir iddiayı sınırlar. En iyi çıkarım, kanıtın izin verdiği kapsamı korur ve alan bilgisini metnin yerine koymaz.', example:'A survey of first-year students found that those who joined a peer study group reported higher confidence. The survey measured confidence, not final grades.', question:'Which conclusion is safest?', options:['Peer groups guarantee higher grades.','The study proves peer groups cause academic success.','The reported association suggests peer groups may support confidence, while effects on grades remain untested.','Students who study alone cannot succeed.'], answer:2, explanation:'The conclusion keeps the association and the measured outcome separate. It does not claim causation or generalise beyond the sample.', transfer:'Bir YÖKDİL paragrafında ölçülen değişken ile ölçülmeyen sonucu iki ayrı not olarak yazın.' },
  ],
};
