// Original short practice lessons. These are previews, not official exam material.
export const lessons = {
  IELTS: [
    {
      id: 'ielts-position', skill: 'Writing', title: 'Make your position unmistakable', duration: '8 min',
      concept: 'An opinion essay needs a position that answers the precise question. A balanced position is possible, but the reader must know what you think and why.',
      example: 'Prompt: Some people think public transport should be free for everyone. To what extent do you agree or disagree?',
      question: 'Which opening gives a clear, qualified position that can guide the whole essay?',
      options: ['Public transport is a controversial topic with many advantages and disadvantages.', 'Although free travel could reduce car use, I support subsidised fares rather than universal free access because funding must remain reliable.', 'This essay will discuss public transport and provide a conclusion.', 'Public transport is used by many people in different countries around the world.'],
      answer: 1,
      explanation: 'The second opening states the extent of agreement and introduces a reason. The other openings announce a topic without answering the question.',
      transfer: 'Write your own two-sentence introduction. State your position, then identify a reason you can develop.',
    },
    {
      id: 'ielts-evidence', skill: 'Reading', title: 'Separate false from not given', duration: '6 min',
      concept: 'False means the passage contradicts the statement. Not Given means the passage does not supply enough information to decide. Do not fill the gap with outside knowledge.',
      example: 'A city library extended its opening hours in May. Staff recorded more evening visits in June than in April. The report did not examine visitors’ ages.',
      question: 'Statement: Most of the additional evening visitors were university students.',
      options: ['True', 'False', 'Not Given'],
      answer: 2,
      explanation: 'The passage reports a change in visits but gives no evidence about who made the additional visits. It neither confirms nor contradicts the statement.',
      transfer: 'List the words you would need to see in the passage before this statement could be True.',
    },
    {
      id: 'ielts-correction', skill: 'Listening', title: 'Notice a speaker’s correction', duration: '5 min',
      concept: 'A speaker may give an initial answer and then correct it. Use this transcript exercise to practise following the final decision before trying the same strategy with audio.',
      example: 'Transcript: “Let’s meet by the main entrance at quarter past six. Actually, the doors there close early. Use the side gate instead, and make it half past six so everyone can arrive.”',
      question: 'What are the final meeting arrangements?',
      options: ['Main entrance, 6:15', 'Side gate, 6:15', 'Main entrance, 6:30', 'Side gate, 6:30'],
      answer: 3,
      explanation: '“Actually” introduces two corrections: the side gate replaces the main entrance, and half past six replaces quarter past six. This is transcript analysis, not a listening score.',
      transfer: 'Note the correction signals. In your next audio practice, wait for the complete exchange before confirming an answer.',
    },
    {
      id: 'ielts-develop', skill: 'Speaking', title: 'Develop an answer naturally', duration: '7 min',
      concept: 'A useful spoken answer moves from a direct response to a reason and a concrete detail. Practise flexible development rather than memorising a script.',
      example: 'Question: Is there a place in your town where you like spending time?',
      question: 'Which answer is most clearly developed with a relevant personal detail?',
      options: ['I often go to the riverside park because it is quiet. Last Sunday, I took a book there and stayed until sunset.', 'Yes, I like a place very much and it is a place that I like.', 'The infrastructure of municipal leisure is a multifaceted phenomenon.', 'There are many places, such as parks, shops, schools, offices and streets.'],
      answer: 0,
      explanation: 'The first answer names the place, explains the preference, and makes it concrete. Complexity alone does not make an answer effective.',
      transfer: 'Speak about your own place for 60 seconds. Notice whether each extra detail helps the listener picture it.',
    },
  ],
  SAT: [
    {
      id: 'sat-inference', skill: 'Information & Ideas', title: 'Keep the inference within the evidence', duration: '7 min',
      concept: 'A supported inference must follow from the text. Reject answers that introduce a cause, comparison or certainty the passage does not establish.',
      example: 'Researchers found that one species of urban bird began singing earlier on streets illuminated throughout the night than on streets where lamps switched off at midnight. The researchers noted that traffic noise also differed between the two types of street.',
      question: 'Which conclusion is best supported by the text?',
      options: ['Artificial light is the only factor that changes when urban birds sing.', 'Birds on unlit streets never sing before sunrise.', 'The observations are consistent with an influence of night lighting, but another environmental difference complicates that interpretation.', 'Switching lamps off at midnight will restore the singing schedule of every urban bird species.'],
      answer: 2,
      explanation: 'The evidence shows an association and explicitly identifies a possible confounding factor. It does not isolate light as the cause or support universal claims.',
      transfer: 'Explain why “only” and “every” make two of the alternatives stronger than the evidence allows.',
    },
    {
      id: 'sat-context', skill: 'Craft & Structure', title: 'Read the context before the word', duration: '6 min',
      concept: 'Choose the meaning that fits the specific sentence. A familiar dictionary meaning may be wrong in context; predict the sense before comparing options.',
      example: 'Although the museum’s early reports praised the restoration, the newly discovered correspondence offers a more qualified assessment: several repairs were effective, but others permanently obscured original details.',
      question: 'As used in the text, “qualified” most nearly means',
      options: ['professionally certified.', 'limited by reservations.', 'completely favourable.', 'expressed in numerical terms.'],
      answer: 1,
      explanation: 'The assessment recognises successes but adds reservations about damage. The contrast after the colon rules out an entirely favourable or purely numerical reading.',
      transfer: 'Replace “qualified” with a short phrase of your own, then reread the sentence to check the meaning.',
    },
    {
      id: 'sat-boundaries', skill: 'Standard English Conventions', title: 'Find the sentence boundary', duration: '6 min',
      concept: 'Two independent clauses need an appropriate boundary. A conjunctive adverb such as “however” does not by itself join them; a semicolon can separate the clauses.',
      example: 'The team expected the pigment to fade quickly ____ however, after six months its colour remained unchanged.',
      question: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
      options: [',', 'and', ': however,', ';'],
      answer: 3,
      explanation: 'Both sides contain an independent clause. A semicolon before “however” and the existing comma after it form a correct boundary. A comma alone creates a comma splice.',
      transfer: 'Identify the subject and verb of each independent clause before choosing punctuation.',
    },
    {
      id: 'sat-transitions', skill: 'Expression of Ideas', title: 'Name the relationship first', duration: '5 min',
      concept: 'Before choosing a transition, describe how the next sentence relates to the previous one: contrast, result, example or continuation.',
      example: 'The seed coating retained moisture during dry periods. ____ seedlings treated with the coating survived longer than untreated seedlings in the same soil.',
      question: 'Which choice completes the text with the most logical transition?',
      options: ['Consequently,', 'Nevertheless,', 'For comparison,', 'On the contrary,'],
      answer: 0,
      explanation: 'Longer survival is presented as a result of moisture retention. The other choices signal contrast or comparison rather than this cause-and-effect relationship.',
      transfer: 'Explain the relationship without using a transition word. Then see whether “as a result” fits.',
    },
  ],
};
